resume_from_checkpoint_path: null 
result_path: "./result"
pretrained_model_name_or_path: "naver-clova-ix/donut-base"
dataset_name_or_paths: "../dataset/synthesize_npdata"
sort_json_key: True
train_batch_sizes: [8]             # Increase to speed up training if GPU allows
val_batch_sizes: [8]
max_epochs: 15                  # 8–12 epochs are ideal for small datasets :contentReference[oaicite:4]{index=4}
max_steps: -1                      # Use epoch-based training
max_length: 64
align_long_axis: True
num_nodes: 1
num_training_samples_per_epoch: 1500
input_size: [1280, 960]            # Default size for Donut
warmup_steps: 200                  # Shorter warmup on small dataset
learning_rate: 5e-5                # Lower LR to avoid overfitting
weight_decay: 0.01
check_val_every_n_epochs: 1
gradient_clip_val: 1.0
seed: 2022
val_check_interval: 1.0
exp_name: "simpletext"
exp_version: "v001"
num_workers: 8
verbose: True
